# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do 
  desc "Distribution to firebase internal"
  lane :ios_build do
    increment_build_number  # auto-increment build
    increment_version_number(version_number: "1.1.5")
    build_ios_app(
    scheme: "testing",
    configuration: "Release",
    export_method: "development",
    clean:true,
    output_directory: "./build", # Ensure we know where the IPA is saved
    output_name: "testing.ipa"   # So you can refer to it directly
    ) 
   
    firebase_app_distribution(
      app: ENV["APP_ID"],
      ipa_path: "./build/testing.ipa", 
      service_credentials_file: "firebase-app-distribution.json",
      googleservice_info_plist_path: "GoogleService-Info.plist",
      #testers: "destinyifehor@gmail.com",
      release_notes: "fixes",
      groups: "testers",
      debug:true
    )
  end
end
