name: iOS CI build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          sudo gem install cocoapods
          sudo gem install fastlane
          npm install

      - name: Install iOS dependencies (Pods) and run fastlane
        working-directory: ios
        run: |
          pod install
          fastlane ios_build
