name: iOS CI build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Install CocoaPods
        run: |
          sudo gem install cocoaPods
          cd ios    
          pos install
          cd ..

      - name: Install Fastlane
        run: |
          gem install fastlane

      - name: Build and upload iOS app
        env:
          FIREBASE_IOS_APP_ID: ${{secrets.FIREBASE_IOS_APP_ID}}
          CREDENTIAL_FILE_CONTENT: ${{secrets.CREDENTIAL_FILE_CONTENT}}
        run: |
          cd ios 
          fastlane ios_build
